
server:
  # port: 8081
  forward-headers-strategy: framework


spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  config:
    import: optional:file:.env[.properties]
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/api/oauth/google/callback"
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  logging:
    level:
      root: info
      com.jobdam: debug
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: none  # in development (auto table create/modify)
      # ddl-auto: none  # in operation (manual sql management)
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: "jobdamoffice@gmail.com"
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
port-one:
  base-url: ${PORTONE_BASE_URL}
  api-key:    ${PORTONE_API_KEY}
  api-secret: ${PORTONE_API_SECRET}
  customer-code: ${PORTONE_CUSTOMER_CODE}
  test-mode: false