server:
  port: 8081  # 8080
  forward-headers-strategy: framework

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: none  # in development (auto table create/modify)
      # ddl-auto: none  # in operation (manual sql management)
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true